CREATE DATABASE ecom_dbms_p1;
USE ecom_dbms_p1;
CREATE TABLE supplier (
    SUPP_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    SUPP_NAME VARCHAR(50) NOT NULL,
    SUPP_CITY VARCHAR(50) NOT NULL,
    SUPP_PHONE VARCHAR(50) NOT NULL
);
create TABLE customer (
	CUS_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CUS_NAME VARCHAR(20) NOT NULL,
    CUS_PHONE VARCHAR(10) NOT NULL,
    CUS_CITY VARCHAR(30) NOT NULL,
    CUS_GENDER CHAR
);
CREATE TABLE category (
	CAT_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CAT_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE product (
	PRO_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PRO_NAME VARCHAR(20) NOT NULL DEFAULT "Dummy",
    PRO_DESC VARCHAR(60),
    CAT_ID INT UNSIGNED,
    FOREIGN KEY (CAT_ID)
		REFERENCES category (CAT_ID)
);






    









    